/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladores;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jrizz_000
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }
    File file;
    String contenidoArchivo;
    String analisisLexico;
    String analisisSintactico;
    String url="http://localhost:8082/";
    String resultadoHtml;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setText("Compilar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Resultados");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("pagina web resultante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Errores lexicos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Errores sintacticos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem5.setText("Manual usuario");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Manual tecnico");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Acerca de");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void analisisLexico() {
        Reader lector;
        try {
            lector = new BufferedReader(new FileReader(file));
               Lexer lexer = new Lexer(lector);
         
         String resultado ="";
         while(true) {
             Tokens tokens = lexer.yylex();
             if(tokens==null){
                 resultado+="FIN";
                 analisisLexico=resultado;
                 return;    
             }
             
             switch(tokens) {
                 case ERROR: {
                     resultado += tokens.ERROR + ": \t \t <simbolo no definido> \n";
                     resultadoHtml += "<tr><td> "+tokens.ERROR +"</td> <td> -Simbolo no definido- </td> </tr> \n";
                 }
                     break;
                  case Identificador: case Numero: case Boton:
                  case Salto: case EtiquetaTexto: case CajaTexto: case Tabla: case EtiquetaTabla:
                  case Fila: case CeldaEncabezado: case Celda: case AbreEtiqueta: case CierraEtiqueta:
                  case InicioPrograma:  case Borde: case Comilla: case Igual: {
                     resultado += lexer.lexeme + ": \t \t <"+ tokens +"> \n";
                     resultadoHtml += "<tr><td> "+lexer.lexeme +"</td> <td> -"+ tokens +"- </td> </tr> \n";
                  }
                     break;    
                 default:
                     resultado+= "Token: \t \t <"+tokens +"> \n";
                     break;
             }
             
         }
      
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void analisisSintactico() {
       
            sintax s = new sintax(new compiladores.LexerCup(new StringReader(contenidoArchivo)));
        try {
            s.parse();
            analisisSintactico="Analisis realizado correctamente";
            //jTextArea1.setText("Analisis realizado correctamente ");
           // jTextArea1.setForeground(new Color(25,111,61));
        } catch (Exception ex) {
           Symbol sym = s.getS();
           analisisSintactico="Error de sintaxis en la linea: "+(sym.right+1) + " Columna: "+(sym.left+1)+" Texto: \""+ sym.value +"\" ";
         
        }
    }
    
    
    public void crearArchivo(String str, String nombreArchivo, String path, String extension){
             try {
     FileWriter myWriter = new FileWriter(path+"\\"+nombreArchivo+extension);
      myWriter.write(str);
      myWriter.close();
      System.out.println("creacion de rchivo exitoso");
    } catch (IOException e) {
      System.out.println("ocurrio un error");
      e.printStackTrace();
    }
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        // AQUI MOSTRAR ERRORES LEXICO 
        jTextArea1.setText(analisisLexico);
        String encabezado="<html> <head><title>ARCHIVO DE SALIDA</title></head> \n <body>";
        String cierre="\n </body> \n </html> ";
        String str="";
        
        str+="<table> \n";
        str+=resultadoHtml;
        str+="</table>";
        
        str=encabezado+str+cierre;
        
        Path rutaXampp = Paths.get("C:\\xampp\\htdocs\\lexico.html");
         if(Files.exists(rutaXampp)) {
            try {
                Files.delete(rutaXampp);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
         crearArchivo(str,"lexico","C:\\xampp\\htdocs",".html");
         
        
             String direccion = url+"/lexico.html";
             direccionar(direccion);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        // AQUI MOSTRAR ERRORES SINTACTICO 
        jTextArea1.setText(analisisSintactico);
        String encabezado="<html> <head><title>ARCHIVO DE SALIDA</title></head> \n <body>";
        String cierre="\n </body> \n </html> ";
        String str="";
        
        analisisSintactico.replace("\n", "<br>");
        
        str=encabezado+analisisSintactico+cierre;
        
        Path rutaXampp = Paths.get("C:\\xampp\\htdocs\\sintactico.html");
         if(Files.exists(rutaXampp)) {
            try {
                Files.delete(rutaXampp);
            } catch (IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
         crearArchivo(str,"sintactico","C:\\xampp\\htdocs",".html");
         
        
             String direccion = url+"/sintactico.html";
             direccionar(direccion);
        
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    
    public void direccionar(String direccion){
         try
                    {
                        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + direccion);
                    }
                    catch(Exception err)
                    {
                        JOptionPane.showMessageDialog(null,"Error: "+err);
                    }
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
         file = jFileChooser1.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
         // textarea.read( new FileReader( file.getAbsolutePath() ), null );
        jTextArea1.setText("");
         BufferedReader  leer = new BufferedReader(new FileReader(file));
         String linea = leer.readLine();
         
         while(linea!=null) {
             jTextArea1.append(linea+"\n");
             linea = leer.readLine();
         }
         
         contenidoArchivo= jTextArea1.getText();
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
     
  String datos="Sandy Arleth López Morales \t 1890-17-23444 \n"; 
  datos+="Wilcer Selmedy Catalan Orozco \t 1890-17-3278 \n";
  datos+="Yanira Lisbeth Xot Cruz \t 1890-16-7195 \n";
  datos+="Seidy Vanessa Martínez Garrido\t 1890-17-1583 \n";
  
    jTextArea1.setText(datos);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        //Compilar
        analisisLexico();
        String show="se ha realizado el analisis lexico,\n para verificar ve al menu ->Resultado ->Errores lexicos \n \n \n";
        jTextArea1.setText(show);
        analisisSintactico();
        show=show+"se ha realizado el analisis sintactico, \n para verificar ve al menu ->Resultado ->Errores sintacticos";
        jTextArea1.setText(show);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        //Mostrar pagina web
       
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         CrearHtml crear = new CrearHtml();
        try {
            crear.generarHtml(contenidoArchivo);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
