
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 30 14:11:36 CST 2020
//----------------------------------------------------

package compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CajaTexto = 6;
  public static final int Celda = 11;
  public static final int Numero = 18;
  public static final int Tabla = 7;
  public static final int Borde = 15;
  public static final int Fila = 9;
  public static final int EtiquetaTabla = 8;
  public static final int AbreEtiqueta = 12;
  public static final int ERROR = 19;
  public static final int CeldaEncabezado = 10;
  public static final int Identificador = 14;
  public static final int EtiquetaTexto = 5;
  public static final int Salto = 4;
  public static final int CierraEtiqueta = 13;
  public static final int EOF = 0;
  public static final int InicioPrograma = 2;
  public static final int Comilla = 17;
  public static final int Linea = 20;
  public static final int error = 1;
  public static final int Igual = 16;
  public static final int Boton = 3;
}

